docker_version: docker-ce-18.03.1.ce-1.el7.centos

swarm_init_server: 192.168.95.130

remote_temp: ~/ansible_temp

local_temp: ~/temp

jenkins_git: git@github.com:randy0098/jenkins-home.git
jenkins_git_version: ultra-permission-3.0-docker
ansible_permission_git: git@github.com:randy0098/ansible-ci.git
ansible_permission_git_version: ultra-permission-3.0-docker
m2_git: git@github.com:randy0098/m2.git

env: prodwh

portainer_port: 9000
portainer_agent_port: 9001
jenkins_port1: 9010
jenkins_port2: 9011
adminer_port: 9020
phpRedisAdmin_port: 9030

mysql_mount_data: "{{env}}_mysql"
mysql_ports:
  devwh: 8100
  testwh: 8200
  preprodwh: 8300
  prodwh: 8400
mysql_port: "{{mysql_ports[env]}}"

redis_mount_data: "{{env}}_redis"
redis_ports:
  devwh: 8110
  testwh: 8210
  preprodwh: 8310
  prodwh: 8410
redis_port: "{{redis_ports[env]}}"

tomcat_name: permission
tomcat_mount_data: "{{env}}_tomcat_{{tomcat_name}}"
tomcat_ports:
  permission:
    devwh: 8120
    testwh: 8220
    preprodwh: 8320
    prodwh: 8420
  cas:
    devwh: 8130
    testwh: 8230
    preprodwh: 8330
    prodwh: 8430
tomcat_port: "{{tomcat_ports[tomcat_name][env]}}"



