dependance_gits:
  ultra_permission_data: git@192.168.194.114:whdev-backend/ultra-permission-data.git
  ultra_permission_client: git@192.168.194.114:whdev-backend/ultra-permission-client.git
  ultra_permission_cas_client: git@192.168.194.114:whdev-backend/ultra-permission-cas-client.git

dependance_git: "{{dependance_gits[dependance_name]}}"

dependance_dir: "{{build_dir_env}}/{{dependance_name}}"
dependance_version: "{{ dependance_commitId if dependance_commitId != '' else branchName }}"

frontend_git: git@192.168.194.114:whdev-frontend/ultra-permission-frontend.git
permission_server_git: git@192.168.194.114:whdev-backend/ultra-permission-server.git

manager_git: git@192.168.194.114:whdev/license/LicenseManagePlatform.git
manager_version: "{{ manager_commitId if manager_commitId != '' else branchName }}"

frontend_version: "{{ frontend_commitId if frontend_commitId != '' else branchName }}"
backend_version: "{{ backend_commitId if backend_commitId != '' else branchName }}"


build_dir: /root/build/ultra-license
build_dir_env: "{{build_dir}}/{{env}}"

frontend_dir: "{{build_dir_env}}/permission-web"
frontend_dist: "{{frontend_dir}}/dist/"
frontend_app_dir: "{{frontend_dir}}/{{appName}}"
tomcat_dir: /glusterfs_mnt/{{env}}_tomcat_permission/tomcat
deploy_name: ultra-permission

backend_dir: "{{build_dir_env}}/permission"
backend_module_dir: "{{backend_dir}}/ultra-permission-server"
backend_target_dir: "{{backend_module_dir}}/target"
module_name: "{{module_name_origin.stdout_lines[1]|replace(' ', '')|replace('<artifactId>', '')|replace('</artifactId>', '')}}"
module_version: "{{module_version_origin.stdout|replace(' ', '')|replace('<version>', '')|replace('</version>', '')}}"
backend_build_name: "{{module_name}}-{{module_version}}"
backend_build_dir: "{{backend_target_dir}}/{{backend_build_name}}"
backend_war_name: ultra-permission.war


remote_temp: ~/build/{{env}}

appNameToFolderName:
  web: web
  
appFolder: "{{appNameToFolderName[appName]}}"

manager_dir: "{{build_dir_env}}/manager"
cas_module_dir: "{{cas_dir}}/"
cas_target_dir: "{{cas_module_dir}}/target"
cas_war_name: ultra-permission-cas-server.war
cas_tomcat_dir: /glusterfs_mnt/{{env}}_tomcat_cas/tomcat
cas_deploy_name: ultra-cas

envToConfig:
  devwh: devwh.json
  testwh: testwh.json
  preprodwh: preprodwh.json
  prodwh: prodwh.json

configFile: "{{envToConfig[env]}}"

envToActive:
  devwh: devwh
  testwh: testwh
  preprodwh: preprodwh
  prodwh: prodwh
  
spring_profiles_active: "{{envToActive[env]}}"
spring_profiles_active_old: "devwh"

envToSwagger:
  devwh: true
  testwh: true
  preprodwh: false
  prodwh: false

swagger_active: "{{envToSwagger[env]}}"

