docker_version: docker-ce-18.03.1.ce-1.el7.centos

swarm_init_server: 10.0.0.102

remote_temp: ~/ansible_temp

local_temp: ~/temp

jenkins_git: git@github.com:randy0098/jenkins-workspace.git

env: test

tomcat_ports:
  dev: 8103
  test: 8203
  pre_prod: 8303
  prod: 8403

tomcat_port: "{{tomcat_ports[env]}}"

