swarm_service_ip: 192.168.95.130
mysql_restore: false
mysql_image: mysql:5.7
mysql_root_password: Ultra-123
zabbix_web_port: 9090

docker_version: docker-ce-18.03.1.ce-1.el7.centos

swarm_init_server: 192.168.95.130

remote_temp: ~/ansible_temp

local_temp: ~/temp

jenkins_git: git@github.com:randy0098/jenkins-home.git
jenkins_git_version: ultra-permission-3.1-docker
ansible_git: git@github.com:randy0098/ansible-ci.git
ansible_git_permission_version: ultra-permission-3.1-docker
ansible_git_license_version: ultra-license-2.0-docker
m2_git: git@github.com:randy0098/m2.git

env: prodwh

portainer_port: 9000
portainer_agent_port: 9001
jenkins_port1: 9010
jenkins_port2: 9011
adminer_port: 9020
phpRedisAdmin_port: 9030

mysql_mount_data: "{{env}}_mysql"
mysql_ports:
  devwh: 8100
  testwh: 8200
  preprodwh: 8300
  prodwh: 8400
  all: 8900
mysql_port: "{{mysql_ports[env]}}"

redis_mount_data: "{{env}}_redis"
redis_ports:
  devwh: 8110
  testwh: 8210
  preprodwh: 8310
  prodwh: 8410
redis_port: "{{redis_ports[env]}}"

tomcat_name: permission
tomcat_mount_data: "{{env}}_tomcat_{{tomcat_name}}"
tomcat_ports:
  permission:
    devwh: 8120
    testwh: 8220
    preprodwh: 8320
    prodwh: 8420
  cas:
    devwh: 8130
    testwh: 8230
    preprodwh: 8330
    prodwh: 8430
  licenseManager:
    devwh: 8140
    testwh: 8240
    preprodwh: 8340
    prodwh: 8440    
  licenseClient:
    devwh: 8150
    testwh: 8250
    preprodwh: 8350
    prodwh: 8450     
tomcat_port: "{{tomcat_ports[tomcat_name][env]}}"



