frontend_git: git@192.168.194.114:iscloud-frontend/iscloud-web.git
backend_git: git@192.168.194.114:iscloud-backend/iscloud.git
version: "{{ commitId if commitId != '' else branchName }}"

frontend_dir: /root/build/iscloud-web
frontend_dist: "{{frontend_dir}}/dist/"
frontend_app_dir: "{{frontend_dir}}/{{appName}}"

backend_dir: /root/build/iscloud
backend_module_dir: "{{backend_dir}}/iscloud-platform/platform"
backend_target_dir: "{{backend_module_dir}}/target"
module_name: "{{module_name_origin.stdout|replace(' ', '')|replace('<name>', '')|replace('</name>', '')}}"
module_version: "{{module_version_origin.stdout|replace(' ', '')|replace('<name>', '')|replace('</name>', '')}}"
backend_build_name: "{{module_name}}-{{module_version}}"
backend_build_dir: "{{backend_target_dir}}/{{backend_build_name}}"
backend_war_name: iscloud-build.war


# sdk_module_dir: "{{backend_dir}}/iscloud-sdk-server"
# sdk_target_dir: "{{sdk_module_dir}}/target"
# sdk_build_name: iscloud-sdk-server-2.2.0-RELEASE
# sdk_build_dir: "{{sdk_target_dir}}/{{sdk_build_name}}"
# sdk_war_name: sdk-build.war

configFile: prodConfig_CI.json

remote_temp: /root/build

appNameToFolderName:
  appMarket: mall
  personalConsole: pc
  internalOperation: pm
  enterpriseOperation: em

# appName: appMarket  
# branchName: release-v2.3.0
# operation: deploy

appFolder: "{{appNameToFolderName[appName]}}"

# env: web_dev_142


