manager_git: git@192.168.194.114:whdev/license/LicenseManagePlatform.git
manager_version: "{{ manager_commitId if manager_commitId != '' else branchName }}"
client_git: git@192.168.194.114:whdev/license/license-client.git
client_version: "{{ client_commitId if client_commitId != '' else branchName }}"

build_dir: /root/build/ultra-license
build_dir_env: "{{build_dir}}/{{env}}"

remote_temp: ~/build/{{env}}

manager_dir: "{{build_dir_env}}/manager"
manager_module_dir: "{{manager_dir}}"
manager_target_dir: "{{manager_module_dir}}/target"
manager_module_name: "{{module_name_origin.stdout|replace(' ', '')|replace('<artifactId>', '')|replace('</artifactId>', '')}}"
manager_module_version: "{{module_version_origin.stdout|replace(' ', '')|replace('<version>', '')|replace('</version>', '')}}"
manager_artifact_name: "{{manager_module_name}}-{{manager_module_version}}.war"
manager_war_name: LicenseManagePlatform.war
manager_tomcat_dir: /glusterfs_mnt/{{env}}_tomcat_licenseManager/tomcat
manager_deploy_name: licenseManager

client_dir: "{{build_dir_env}}/client"
client_module_dir: "{{client_dir}}/LicenseClientValidate"
client_target_dir: "{{client_module_dir}}/target"
client_module_name: "{{module_name_origin.stdout_lines[1]|replace(' ', '')|replace('<artifactId>', '')|replace('</artifactId>', '')}}"
client_module_version: "{{module_version_origin.stdout|replace(' ', '')|replace('<version>', '')|replace('</version>', '')}}"
client_artifact_name: "{{client_module_name}}-{{client_module_version}}.war"
client_war_name: LicenseClientValidate.war
client_tomcat_dir: /glusterfs_mnt/{{env}}_tomcat_licenseClient/tomcat
client_deploy_name: licenseClientValidate

envToActive:
  devwh: devwh
  testwh: testwh
  preprodwh: preprodwh
  prodwh: prodwh
  
spring_profiles_active: "{{envToActive[env]}}"
spring_profiles_active_old: "devwh"

envToSwagger:
  devwh: true
  testwh: true
  preprodwh: false
  prodwh: false

swagger_active: "{{envToSwagger[env]}}"

