glusterfs_mnt: /glusterfs_mnt
docker_mnt: /docker_mnt
mnt: "{{glusterfs_mnt}}"

swarm_service_ip: 192.168.95.130
mysql_restore: false
mysql_image: mysql:8.0.12
mysql_root_password: Ultra-123
zabbix_web_port: 9090

docker_version: docker-ce-18.03.1.ce-1.el7.centos

swarm_init_server: 192.168.95.130

remote_temp: ~/ansible_temp

local_temp: ~/temp

jenkins_git: git@github.com:randy0098/jenkins-home.git
jenkins_git_version: ultra-permission-3.1-docker
ansible_git: git@github.com:randy0098/ansible-ci.git
ansible_git_permission_version: ultra-permission-3.1-docker
ansible_git_license_version: ultra-license-2.0-docker
m2_git: git@github.com:randy0098/m2.git

env: prodwh

portainer_port: 9000
portainer_agent_port: 9001
jenkins_port1: 9010
jenkins_port2: 9011
adminer_port: 9020
phpRedisAdmin_port: 9030
readis_port: 9031
redis_stat_port: 9032
redis_commander_port: 9033
phpredmin_port: 9034
icinga2_port: 9040

mysql_mount_data: "{{env}}_mysql"
mysql_ports:
  devwh: 8100
  testwh: 8200
  preprodwh: 8300
  prodwh: 8400
  bigdatatest: 8500
  mysql1: 8810
  mysql2: 8820
  all: 8900
mysql_port: "{{mysql_ports[env]}}"

redis_mount_data: "{{env}}_redis"
redis_ports_standalone:
  devwh: 8110
  testwh: 8210
  preprodwh: 8310
  prodwh: 8410
  bigdatatest: 8510
redis_port_standalone: "{{redis_ports_standalone[env]}}"

# redis_ports_cluster:
#   devwh:
#     redis1: 8111
#     redis2: 8112
#     redis3: 8113
#     redis4: 8114
#     redis5: 8115
#     redis6: 8116
#   testwh:
#     redis1: 8211
#     redis2: 8212
#     redis3: 8213
#     redis4: 8214
#     redis5: 8215
#     redis6: 8216
#   preprodwh:
#     redis1: 8311
#     redis2: 8312
#     redis3: 8313
#     redis4: 8314
#     redis5: 8315
#     redis6: 8316

# redis_cluster:
#   devwh:
#     redis1: 
#       ip: 192.168.95.130
#       port: 8111
#     redis2: 
#       ip: 192.168.95.130
#       port: 8112
#     redis3: 
#       ip: 192.168.95.131
#       port: 8113      
#     redis4: 
#       ip: 192.168.95.131
#       port: 8114      
#     redis5: 
#       ip: 192.168.95.132
#       port: 8115     
#     redis6: 
#       ip: 192.168.95.132
#       port: 8116      

# redis_name_cluster
# redis_ip_cluster
# redis_port_cluster 


tomcat_name: permission
tomcat_mount_data: "{{env}}_tomcat_{{tomcat_name}}"
tomcat_ports:
  permission:
    devwh: 8120
    testwh: 8220
    preprodwh: 8320
    prodwh: 8420
    bigdatatest: 8520
  cas:
    devwh: 8130
    testwh: 8230
    preprodwh: 8330
    prodwh: 8430
    bigdatatest: 8530
  licenseManager:
    devwh: 8140
    testwh: 8240
    preprodwh: 8340
    prodwh: 8440    
  licenseClient:
    devwh: 8150
    testwh: 8250
    preprodwh: 8350
    prodwh: 8450     
tomcat_port: "{{tomcat_ports[tomcat_name][env]}}"


nginx_mount_data: "{{env}}_nginx"
# nginx_cluster:
#   devwh:
#     nginx1: 
#       ip: 192.168.95.130
#       port: 8161
#     nginx2: 
#       ip: 192.168.95.131
#       port: 8162

# nginx_ip_cluster
# nginx_port_cluster

keepalived_mount_data: "{{env}}_keepalived"
# keepalived_cluster:
#   devwh:
#     keepalived1: 
#       ip: 192.168.95.130
#       port: 8171
#     keepalived2: 
#       ip: 192.168.95.131
#       port: 8172

# keepalived_ip_cluster
# keepalived_port_cluster

kafka_mount_data: "{{env}}_kafka"
kafka_ports_standalone:
  devwh: 8180
kafka_port_standalone: "{{kafka_ports_standalone[env]}}"

zookeeper_mount_data: "{{env}}_kafka"
kafka_ports_standalone:
  devwh: 8180
kafka_port_standalone: "{{kafka_ports_standalone[env]}}"



