version: '3.2'

services:

  zabbix_server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.4.14
    environment:
      DB_SERVER_HOST: "{{swarm_service_ip}}"
      DB_SERVER_PORT: "{{mysql_ports[env]}}"
      MYSQL_ROOT_PASSWORD: "{{mysql_root_password}}"
      ZBX_DEBUGLEVEL: 3
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "10051:10051"    