version: '3.2'

services:

  zabbix_server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.4.14
    environment:
      DB_SERVER_HOST: 10.0.0.105
      DB_SERVER_PORT: 8900
      MYSQL_ROOT_PASSWORD: test_123
      ZBX_DEBUGLEVEL: 5
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "10051:10051"
#     networks:
#       - zabbix_network    

# networks:
#   zabbix_network:
#     external: true      