version: '3.2'

services:

  mysql:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Ultra-123
    volumes:    
      - /glusterfs_mnt/{{mysql_mount_data}}/mysql_data:/var/lib/mysql
      - /glusterfs_mnt/{{mysql_mount_data}}/alldb_backup.sql:/docker-entrypoint-initdb.d/alldb_backup.sql
      # - /glusterfs_mnt/{{mysql_mount_data}}/mysql_entrypoint.sh:/root/temp/mysql_entrypoint.sh
      - /etc/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime      
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "{{mysql_port}}:3306"    