version: '3.2'

services:

  jenkins:
    image: jenkins:2.46.2
    ports:
      - 9002:8080   
      - 9003:50000
    volumes:    
      - /glusterfs_mnt/jenkins-workspace:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      user: root
      command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py&&python get-pip.py&&pip install ansible==2.6.2
