---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: git checkout
    git: repo=git@github.com:randy0098/backend.git 
         dest=/root/temp/backendTest
  - name: maven install
    command: chdir=/root/temp/backendTest mvn clean install -fn -Dmaven.test.skip      