---
- name: build frontend
  hosts: localhost
  vars_files: 
  - vars/external_vars.yml
  tasks:
  - name: git checkout
    git: repo={{frontend_git}} 
         dest={{frontend_dir}}
  - name: npm install
    command: chdir={{frontend_dir}} npm install         
  - name: npm build
    command: chdir={{frontend_dir}} npm run build

