---
- name: create frontend build workspace by env
  file: 
    path: "{{frontend_dir}}"
    state: directory 

- name: frontend_compile
  hosts: localhost
  roles:
  - frontend_compile

- name: frontend_deploy
  hosts: "{{env}}"
  roles:
  - { role: frontend_deploy, when: frontend_operation == 'deploy' }
