---
- name: git and npm operation
  hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: git checkout
    git: repo=git@github.com:randy0098/frontend.git 
         dest=/root/temp/frontendTest
  - name: npm build
    command: chdir=/root/temp/frontendTest npm run build

