---
- name: config GlusterFS
  hosts: docker_servers
  tasks:
  - debug:
      var: groups['docker_servers'][0]
  - name: configure the trusted pool
    command: gluster peer probe {{item}}
    loop: "{{groups['docker_servers'][1:]}}"
    when: inventory_hostname == groups['docker_servers'][0]

