---
# - name: config GlusterFS
#   hosts: "{{groups['docker_servers'][0]}}"
#   tasks:
#   - debug:
#       var: groups['docker_servers'][0]
#   - name: configure the trusted pool
#     command: gluster peer probe {{item}}
#     loop: "{{groups['docker_servers'][1:]}}"

# - name: create volume directory
#   hosts: docker_servers
#   tasks:   
#   - name: create gv0 directory
#     file:
#       path: /data/brick1/gv0
#       state: directory

- name: Set up a GlusterFS volume
  hosts: "{{groups['docker_servers'][0]}}"
  vars: 
    var1: "{{groups['docker_servers'] | join(':/data/brick1/gv0 ') + ':/data/brick1/gv0'}}"
  tasks:
  - debug:
      var: var1              
  - debug:
      var: groups['docker_servers'] | join(":/data/brick1/gv0 ") + ":/data/brick1/gv0"
   