---
- name: install GlusterFS
  hosts: docker_servers
  tasks:
  - name: create brick directory
    file:
      path: /data/brick1
      state: directory
  - name: format and mount the bricks
    shell: echo '/dev/mapper/centos-root /data/brick1 xfs defaults 0 0' >> /etc/fstab && mount -a && mount
  - name: installing GlusterFS
    yum: 
      name: centos-release-gluster,glusterfs-server 
      state: present
  - name: start glusterfs-server
    service: 
      name: glusterd.service 
      state: started
      enabled: yes    
  
       

