---
- name: config GlusterFS
  hosts: groups['docker_servers'][0]
  tasks:
  - debug:
      var: groups['docker_servers'][0]
  - name: configure the trusted pool
    command: gluster peer probe {{item}}
    loop: "{{groups['docker_servers'][1:]}}"

