---
- name: configure the trusted pool
  hosts: "{{groups['docker_servers'][0]}}"
  tasks:
  - debug:
      var: groups['docker_servers'][0]
  - name: configure the trusted pool
    command: gluster peer probe {{item}}
    loop: "{{groups['docker_servers'][1:]}}"

- name: create volume directory
  hosts: docker_servers
  tasks:   
  - name: create volume directory
    file:
      path: /data/brick1/gv0
      state: directory

- name: create volume
  hosts: "{{groups['docker_servers'][0]}}"
  vars: 
    var1: "{{groups['docker_servers'] | length}}"
    var2: "{{groups['docker_servers'] | join(':/data/brick1/gv0 ') + ':/data/brick1/gv0'}}"
    vo_create_cmd: "{{'gluster volume create gv0 replica ' + var1 + ' ' + var2 + ' ' + 'force'}}"
  tasks:
  - debug:
      var: vo_create_cmd
  - name: create volume
    command: "{{vo_create_cmd}}"
  - name: start volume
    command: gluster volume start gv0
   
- name: mount volume
  hosts: docker_servers
  tasks:   
  - name: mount volume
    mount:
      path: /var/lib/docker/volumes
      src: "{{inventory_hostname + ':/gv0'}}"
      fstype: glusterfs
      state: mounted 

    
   