---
- name: config GlusterFS
  hosts: docker_servers
  tasks:
  - debug:
    msg: "System {{ inventory_hostname }}"
  - name: configure the trusted pool
    command: gluster peer probe "{{groups['docker_servers'][1]}}"
    when: inventory_hostname == groups['docker_servers'][0]

