---
- name: install GlusterFS
  hosts: docker_servers
  tasks:
  - name: create brick directory
    file:
      path: /data/brick1
      state: directory
  - name: format and mount the bricks
    shell: echo '/dev/mapper/centos-root /data/brick1 xfs defaults 0 0' >> /etc/fstab && mount -a && mount
  - name: installing GlusterFS
    yum: 
      name: glusterfs-server 
      state: present
       

