---
- name: install GlusterFS
  hosts: docker_servers
  tasks:
  - name: create brick directory
    file:
      path: /data/brick1
      state: directory
  - name: format and mount the bricks
    mount:
      path: /data/brick1
      src: /dev/mapper/centos-root
      fstype: xfs
      state: mounted
  - name: install centos-release-gluster
    yum: 
      name: centos-release-gluster
      state: present
  - name: install glusterfs-server
    yum: 
      name: glusterfs-server 
      state: present    
  - name: start glusterfs-server
    service: 
      name: glusterd.service 
      state: started
      enabled: yes    
  
       

