---
- name: config GlusterFS
  hosts: docker_servers
  tasks:
  - name: configure the trusted pool
    command: gluster peer probe "{{groups['docker_servers'][1][inventory_hostname]}}"
    when: inventory_hostname == groups['docker_servers'][0][inventory_hostname]
