---
- name: compress jenkins and ansible workspace
  hosts: localhost
  tasks:
  - name: create temp directory
    file: 
      path: "{{local_temp}}"
      state: directory
  # - name: git checkout jenkins_home
  #   git: repo={{jenkins_git}}  
  #       dest="{{local_temp}}/jenkins_home"
  #       force=yes
  # - name: compress jenkins_home
  #   archive:
  #     path: "{{local_temp}}/jenkins_home"
  #     dest: "{{local_temp}}/jenkins_home.tgz"

  - name: create ultra-permission directory
    file: 
      path: "{{local_temp}}/ultra-permission"
      state: directory

  - name: git checkout ultra-permission
    git: repo={{ultra_permission_git}}  
        dest="{{local_temp}}/ultra-permission/iscloud-ci"
        version=ultra-permission
        force=yes
  - name: compress ultra-permission
    archive:
      path: "{{local_temp}}/ultra-permission/iscloud-ci"
      dest: "{{local_temp}}/ultra-permission/ultra-permission.tgz"

- name:  deploy jenkins
  hosts: "{{groups['swarm_manager'][0]}}"
  roles:
  - role: jenkins_deploy      