---
# - name: build all
#   hosts: localhost
#   vars_files: 
#   - vars/external_vars.yml
#   tasks:
#   - name: copy appMarket to backend
#     copy: src={{frontend_dir}}/appMarket/dist/ dest={{backend_build_dir}}
#   - name: copy personalConsole to backend
#     copy: src={{frontend_dir}}/personalConsole/dist/ dest={{backend_build_dir}}    
#   - name: copy internalOperation to backend
#     copy: src={{frontend_dir}}/internalOperation/dist/ dest={{backend_build_dir}}
#   - name: copy enterpriseOperation to backend
#     copy: src={{frontend_dir}}/enterpriseOperation/dist/ dest={{backend_build_dir}}        
#   - name: build backend war
#     shell: chdir={{backend_build_dir}} jar -cvfM ../{{backend_war_name}} *

- name: copy war to deploy server
  hosts: web_dev_server
  vars_files: 
  - vars/external_vars.yml
  tasks:
#   - name: clean old remote war
#     command: rm {{remote_temp}}/{{backend_war_name}}  
#   - name: copy war to remote
#     copy: src={{backend_target_dir}}/{{backend_war_name}}
#           dest={{remote_temp}}/{{backend_war_name}}
  - name: stop tomcat
    shell: source /etc/profile sh {{tomcat_dir}}/bin/shutdown.sh
  - name: clean old project folder
    shell: rm -rf {{tomcat_dir}}/webapps/{{deploy_name}}     
  - name: deploy to tomcat
    shell: chdir={{remote_temp}} unzip {{backend_war_name}} -d {{tomcat_dir}}/webapps/{{deploy_name}}
  - name: start tomcat
    shell: source /etc/profile sh {{tomcat_dir}}/bin/startup.sh