---
# - name: build all
#   hosts: localhost
#   vars_files: 
#   - vars/external_vars.yml
#   tasks:
#   - name: copy frontend to backend
#     copy: src={{frontend_dist}} dest={{backend_build_dir}}
#   - name: build backend war
#     shell: chdir={{backend_build_dir}} jar -cvfM ../{{backend_war_name}} *
- name: copy war to deploy server
  hosts: dev_web_server
  vars_files: 
  - vars/external_vars.yml
  tasks:
  # - name: copy war to remote
  #   copy: src={{backend_target}}/{{backend_war_name}}
  #         dest={{remote_temp}}/{{backend_war_name}}
  - name: stop tomcat
    shell: source /etc/profile sh {{tomcat_dir}}/bin/shutdown.sh
  - name: clean old project folder
    shell: rm -rf {{tomcat_dir}}/webapps/{{deploy_name}}     
  - name: deploy to tomcat
    shell: chdir={{remote_temp}} unzip {{backend_war_name}} -d {{tomcat_dir}}/webapps/{{deploy_name}}
  - name: start tomcat
    shell: source /etc/profile sh {{tomcat_dir}}/bin/startup.sh