---
- name: build all
  hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: copy frontend to backend
    copy: src=/root/temp/frontendTest/dist/
          dest=/root/temp/backendTest/backend-web/target/backend-web/
  - name: package
    command: chdir=/root/temp/backendTest/backend-web/target/backend-web/ jar -cvfM ../backend-web-build.war *      

