---
- name:  deploy redis
  hosts: "{{groups['swarm_manager'][0]}}"
  tasks:
  - name: deploy redis
    vars: 
      redis_name_cluster: "{{item.key}}"
      redis_port_cluster: "{{item.value}}"  
    include_role:
      name: redis_deploy_cluster  
    with_dict: "{{redis_ports_cluster[env]}}"  