---
- name:  server init
  hosts: docker_servers
  tasks:
  - name: copy id_rsa
    copy: 
      src: /root/.ssh/id_rsa
      dest: /root/.ssh/id_rsa
      force: no
  - name: copy id_rsa.pub
    copy: 
      src: /root/.ssh/id_rsa.pub
      dest: /root/.ssh/id_rsa.pub
      force: no