- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

# - name: clean redis mount directory
#   file: 
#     path: /glusterfs_mnt/{{redis_mount_data}}
#     state: absent

- name: create redis_name_cluster directory
  file: 
    path: /glusterfs_mnt/{{redis_mount_data}}/{{redis_name_cluster}}
    state: directory

- name: create redis_data directory
  file: 
    path: /glusterfs_mnt/{{redis_mount_data}}/{{redis_name_cluster}}/redis_data
    state: directory

- name: copy redis.conf to remote
  template: 
    src: redis.conf
    dest: /glusterfs_mnt/{{redis_mount_data}}/{{redis_name_cluster}}/redis.conf

- name: copy compose.yml to remote
  template: 
    src: redis_compose.yml 
    dest: "{{remote_temp}}/redis_compose.yml"

- name: deploy docker-compose
  command: docker-compose -f redis_compose.yml -p {{env}}_{{redis_name_cluster}} up -d
  args: 
    chdir: "{{remote_temp}}"    


    