- name: clean portainer mount directory
  file:
    path: /glusterfs_mnt/portainer
    state: absent

- name: create portainer_data mount directory
  file: 
    path: /glusterfs_mnt/portainer/portainer_data
    state: directory 

- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: copy stack.yml to remote
  template: 
    src: portainer-agent-stack.yml 
    dest: "{{remote_temp}}/portainer-agent-stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=portainer-agent-stack.yml portainer 
  args: 
    chdir: "{{remote_temp}}"


    