# - name: get module name
#   command: chdir={{cas_module_dir}} grep <artifactId>  pom.xml -m 2
#   register: module_name_origin

# - name: get module version
#   command: chdir={{cas_module_dir}} grep <version>  pom.xml -m 1
#   register: module_version_origin

# - debug:
#     var: module_name_origin

# - debug:
#     var: module_name

- name: clean cas war
  file: 
    path: "{{build_dir_env}}/{{cas_war_name}}"
    state: absent   
    
# - name: build cas war
#   archive:
#     path: "{{cas_build_dir}}/*"
#     dest: "{{build_dir_env}}/{{cas_war_name}}"
#     format: zip 

- name: build cas war
  copy: 
    src: "{{cas_target_dir}}/{{cas_war_name}}"
    dest: "{{build_dir_env}}/{{cas_war_name}}"