version: '3.2'

services:
  keepalived:
    image: osixia/keepalived:1.2.24
    volumes:
    - "{{docker_mnt}}/{{keepalived_mount_data}}/{{keepalived_name_cluster}}/conf/keepalived.conf:/container/service/keepalived/assets/keepalived.conf"
    cap_add:
    - NET_ADMIN
    network_mode: host
    environment:
    - loglevel=debug   