- name: get module name
  command: chdir={{backend_module_dir}} grep <artifactId>  pom.xml -m 2
  register: module_name_origin

- name: get module version
  command: chdir={{backend_module_dir}} grep <version>  pom.xml -m 1
  register: module_version_origin

- name: debug module_name_origin
  debug:
    var: module_name_origin

- name: debug module_name
  debug:
    var: module_name

- name: copy frontend all apps to backend
  copy:  
    src: "{{frontend_dir}}/{{item.key}}/dist/"
    dest: "{{backend_build_dir}}"
  with_dict: "{{appNameToFolderName}}"
  
- name: clean backend war
  file: 
    path: "{{build_dir_env}}/{{backend_war_name}}"
    state: absent   
    
- name: build backend war
  archive:
    path: "{{backend_build_dir}}/*"
    dest: "{{build_dir_env}}/{{backend_war_name}}"
    format: gz