version: '3.2'

services:

  "{{redis_name_cluster}}":
    image: redis:4.0.11
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:    
      - /glusterfs_mnt/{{redis_mount_data}}/{{redis_name_cluster}}/redis_data:/data
      - /glusterfs_mnt/{{redis_mount_data}}/{{redis_name_cluster}}/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "{{redis_port_cluster}}:6379"
    network_mode: host