---
- name: git checkout
  git: repo={{frontend_git}} 
        dest={{frontend_app_dir}}
        version={{branchName}}
- name: npm install
  command: chdir={{frontend_app_dir}} npm install         
- name: npm build
  command: chdir={{frontend_app_dir}} npm run build --configFile={{configFile}} --app={{appName}}
