---
- name: git checkout
  git: repo={{frontend_git}} 
       dest={{frontend_app_dir}}
       version={{frontend_version}}
       force=yes
- name: npm install
  command: chdir={{frontend_app_dir}} npm install      
- name: npm install babel-plugin-external-helpers
  command: chdir={{frontend_app_dir}} npm install babel-plugin-external-helpers       
- name: npm build
  command: chdir={{frontend_app_dir}} npm run build --configFile={{configFile}} --app={{appName}}
