version: '3.2'

services:

  mysql:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: randy1234
    volumes:    
      - /glusterfs_mnt/mysql_data:/var/lib/mysql
    ports:
      - 8100:3306

  adminer:
    image: adminer
    ports:
      - 9004:8080