version: '3.2'

services:

  zabbix_agent:
    image: zabbix/zabbix-agent:ubuntu-3.4.14
    environment:
      DB_SERVER_HOST: 10.0.0.105
      DB_SERVER_PORT: 8900
      MYSQL_ROOT_PASSWORD: test_123
      ZBX_SERVER_HOST: 10.0.0.107
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Shanghai
      ZBX_DEBUGLEVEL: 3
    # deploy:
    #   mode: global
    # deploy:
    #   restart_policy:
    #     condition: any
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s    
    user: root  
    privileged: true  
    pid: "host"
    restart: always
    # network_mode: host
    ports:
      - "10050:10050"
    networks:
      - zabbix_all_zabbix_network    

networks:
  zabbix_all_zabbix_network:
    external: true        