version: '3.2'

services:

  "{{tomcat_name}}":
    image: tomcat:8.5.32-jre8
    volumes:    
      - /glusterfs_mnt/{{tomcat_mount_data}}/tomcat/webapps:/usr/local/tomcat/webapps
      - /glusterfs_mnt/{{tomcat_mount_data}}/tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - /glusterfs_mnt/{{tomcat_mount_data}}/tomcat/conf/{{server_xml}}:/usr/local/tomcat/conf/server.xml
      - /glusterfs_mnt/{{tomcat_mount_data}}/ssl:/root/ssl
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "{{tomcat_port}}:8080"
    networks:
      - "{{env}}_tomcat_network"
    extra_hosts:
      - "www.iscs.com:{{env}}_tomcat_permission_permission"
      - "www.iscas.com:{{env}}_tomcat_cas_cas"
      - "www.testxf.com:10.0.0.12"

networks:
  "{{env}}_tomcat_network":
    external: true