version: '3.2'

services:

  adminer:
    image: adminer
    deploy:
      mode: replicated
      replicas: 1    
    ports:
      - "{{adminer_port}}:8080" 
    volumes:    
      - /etc/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime       