version: '3.2'

services:

  zabbix_web:
    image: zabbix/zabbix-web-apache-mysql:centos-3.4.14
    environment:
      DB_SERVER_HOST: 10.0.0.105
      DB_SERVER_PORT: 8900
      MYSQL_ROOT_PASSWORD: test_123
      ZBX_SERVER_HOST: 10.0.0.105
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
    networks:
      - zabbix_network    

networks:
  zabbix_network:
    external: true        