version: '3.2'

services:

  redis:
    image: redis:4.0.11
    volumes:    
      - /glusterfs_mnt/redis_data:/data
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8101:6379

  phpRedisAdmin:
    image: erikdubbelboer/phpredisadmin
    ports:
     - 9005:80      
    environment:
      REDIS_1_HOST: redis   
      REDIS_1_NAME: redis                   