<?php declare(strict_types=1);

return [
    [
        'name'          => 'redis-devwh',
        'host'          => '{{swarm_service_ip}}',
        'port'          => "{{redis_ports['devwh']}}",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'redis-testwh',
        'host'          => '{{swarm_service_ip}}',
        'port'          => "{{redis_ports['testwh']}}",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'redis-preprodwh',
        'host'          => '{{swarm_service_ip}}',
        'port'          => "{{redis_ports['preprodwh']}}",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],  
    [
        'name'          => 'redis-cluster-devwh1',
        'host'          => '192.168.95.130',
        'port'          => "8111",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'redis-cluster-devwh2',
        'host'          => '192.168.95.130',
        'port'          => "8112",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'redis-cluster-devwh3',
        'host'          => '192.168.95.131',
        'port'          => "8113",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ], 
    [
        'name'          => 'redis-cluster-devwh4',
        'host'          => '192.168.95.132',
        'port'          => "8114",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'redis-cluster-devwh5',
        'host'          => '192.168.95.133',
        'port'          => "8115",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'redis-cluster-devwh6',
        'host'          => '192.168.95.133',
        'port'          => "8116",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],               
];