<?php declare(strict_types=1);

return [
    [
        'name'          => 'devwh-redis',
        'host'          => '{{swarm_service_ip}}',
        'port'          => "{{redis_ports_standalone['devwh']}}",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'testwh-redis',
        'host'          => '{{swarm_service_ip}}',
        'port'          => "{{redis_ports_standalone['testwh']}}",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'preprodwh-redis',
        'host'          => '{{swarm_service_ip}}',
        'port'          => "{{redis_ports_standalone['preprodwh']}}",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],  
    [
        'name'          => 'devwh-redis1',
        'host'          => '192.168.95.130',
        'port'          => "8111",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'devwh-redis2',
        'host'          => '192.168.95.130',
        'port'          => "8112",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'devwh-redis3',
        'host'          => '192.168.95.131',
        'port'          => "8113",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ], 
    [
        'name'          => 'devwh-redis4',
        'host'          => '192.168.95.131',
        'port'          => "8114",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'devwh-redis5',
        'host'          => '192.168.95.132',
        'port'          => "8115",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],
    [
        'name'          => 'devwh-redis6',
        'host'          => '192.168.95.132',
        'port'          => "8116",
        'auth'          => null,
        'timeout'       => 2.5,
        'retryInterval' => 100,
        'databaseMap'   => [],
    ],               
];