version: '3.2'

services:

  zabbix_server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.4.14
    environment:
      DB_SERVER_HOST: 10.0.0.105
      DB_SERVER_PORT: 8900
      MYSQL_ROOT_PASSWORD: test_123
      ZBX_DEBUGLEVEL: 4
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - zabbix_network      
    ports:
      - "10051:10051"

  zabbix_web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-3.4.14
    environment:
      DB_SERVER_HOST: 10.0.0.105
      DB_SERVER_PORT: 8900
      MYSQL_ROOT_PASSWORD: test_123
      ZBX_SERVER_HOST: 10.0.0.105
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - zabbix_network         
    ports:
      - "80:80"

  zabbix_agent:
    image: zabbix/zabbix-agent:ubuntu-3.4.14
    environment:
      DB_SERVER_HOST: 10.0.0.105
      DB_SERVER_PORT: 8900
      MYSQL_ROOT_PASSWORD: test_123
      ZBX_SERVER_HOST: 10.0.0.105
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Shanghai
      ZBX_DEBUGLEVEL: 4
    deploy:
      mode: global
    networks:
      - zabbix_network         
    user: root  
    privileged: true  
    pid: "host"
    ports:
      - "10050:10050"

networks:
  zabbix_network:
    driver: overlay
    attachable: true