- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: copy stack.yml to remote
  template: 
    src: icinga2_stack.yml 
    dest: "{{remote_temp}}/icinga2_stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=icinga2_stack.yml icinga2
  args: 
    chdir: "{{remote_temp}}"


    