- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: clean tomcat workspace
  file:
    path: /glusterfs_mnt/{{tomcat_name}}
    state: absent

- name: create tomcat webapps
  file: 
    path: /glusterfs_mnt/{{tomcat_name}}/webapps
    state: directory

- name: copy stack.yml to remote
  template: 
    src: tomcat_stack.yml 
    dest: "{{remote_temp}}/tomcat_stack.yml"

- name: debug
  debug:
    var: tomcat_permission_port

# - name: deploy stack
#   command: docker stack deploy --compose-file=tomcat_stack.yml {{tomcat_name}}_{{env}}
#   args: 
#     chdir: "{{remote_temp}}"


    