- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: copy stack.yml to remote
  template: 
    src: phpRedisAdmin_stack.yml 
    dest: "{{remote_temp}}/phpRedisAdmin_stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=phpRedisAdmin_stack.yml phpRedisAdmin
  args: 
    chdir: "{{remote_temp}}"


    