- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: copy stack.yml to remote
  template: 
    src: kafka_stack.yml 
    dest: "{{remote_temp}}/kafka_stack.yml"

- name: debug
  debug:
    var: kafka_port_standalone

- name: debug
  debug:
    var: zookeeper_port_standalone

- name: deploy stack
  command: docker stack deploy --compose-file=kafka_stack.yml {{env}}_kafka
  args: 
    chdir: "{{remote_temp}}"


    