tomcat_dir: /build/apache-tomcat-8.0.49
tomcat_process_keyword: /build/apache-tomcat-8.0.49
deploy_name: platform
config_properties: config.web_dev_142
appContext_job: appContext-job.web_dev_142
