---
- name: git checkout
  git: repo={{backend_git}}  
       dest={{backend_dir}}
       version={{backend_version}}
       force=yes
- name: maven clean platform
  command: chdir={{backend_module_dir}} mvn clean   
- name: maven install
  command: chdir={{backend_dir}} mvn clean install -Dmaven.test.skip -fn
