---
- name: git checkout
  git: repo={{permission_server_git}}  
       dest={{backend_dir}}
       version={{backend_version}}
       force=yes
- name: build permission
  command: chdir="{{backend_dir}}" mvn clean install -Dmaven.test.skip
