---
- name: git checkout
  git: repo={{backend_git}}  
       dest={{backend_dir}}
       version={{backend_version}}
       force=yes
- name: maven install
  command: chdir="{{backend_dir}}/iscloud-platform" mvn clean install -Dmaven.test.skip -fn
