- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: copy stack.yml to remote
  template: 
    src: nginx-stack.yml 
    dest: "{{remote_temp}}/nginx-stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=nginx-stack.yml {{env}}_nginx 
  args: 
    chdir: "{{remote_temp}}"


    