- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: create nginx_name_cluster directory
  file: 
    path: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}
    state: directory

- name: copy nginx.conf to remote
  template: 
    src: nginx.conf
    dest: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/redis.conf

- name: copy stack.yml to remote
  template: 
    src: nginx-stack.yml 
    dest: "{{remote_temp}}/nginx-stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=nginx-stack.yml {{env}}_nginx 
  args: 
    chdir: "{{remote_temp}}"


    