- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: clean nginx mount directory
  file: 
    path: /glusterfs_mnt/{{nginx_mount_data}}
    state: absent

- name: create nginx_name_cluster directory
  file: 
    path: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}
    state: directory

- name: create nginx conf directory
  file: 
    path: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/conf
    state: directory

- name: copy nginx.conf to remote
  template: 
    src: nginx.conf
    dest: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/conf/nginx.conf

- name: copy default.conf to remote
  template: 
    src: default.conf
    dest: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/conf/default.conf

- name: create nginx html directory
  file: 
    path: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/html
    state: directory

- name: copy index.html.master to remote
  template: 
    src: index.html.master
    dest: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/html/index.html  
  when: nginx_type == "master"

- name: copy index.html.slave to remote
  template: 
    src: index.html.slave
    dest: /glusterfs_mnt/{{nginx_mount_data}}/{{nginx_name_cluster}}/html/index.html  
  when: nginx_type == "slave"  

# - name: copy stack.yml to remote
#   template: 
#     src: nginx-stack.yml 
#     dest: "{{remote_temp}}/nginx-stack.yml"

# - name: deploy stack
#   command: docker stack deploy --compose-file=nginx_stack.yml {{env}}_nginx 
#   args: 
#     chdir: "{{remote_temp}}"

- name: copy compose.yml to remote
  template: 
    src: nginx_compose.yml 
    dest: "{{remote_temp}}/nginx_compose.yml"

- name: deploy docker-compose
  command: docker-compose -f nginx_compose.yml -p {{env}}_{{nginx_name_cluster}} up -d
  args: 
    chdir: "{{remote_temp}}"   
    