- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: clean jenkins_workspace
  file: 
    path: /glusterfs_mnt/jenkins_workspace
    state: absent

- name: create jenkins_workspace
  file: 
    path: /glusterfs_mnt/jenkins_workspace
    state: directory

# - name: extract jenkins_workspace.tgz
#   unarchive:
#     src: "{{local_temp}}/jenkins_workspace.tgz"
#     dest: /glusterfs_mnt/

- name: modify directory owner
  file: 
    path: /glusterfs_mnt/jenkins_workspace
    owner: 1000
    group: 1000
    recurse: yes
    state: directory

# - name: modify directory owner
#   command: chown -R 1000:1000 /glusterfs_mnt/jenkins-workspace

- name: copy stack.yml to remote
  copy: 
    src: jenkins_stack.yml 
    dest: "{{remote_temp}}/jenkins_stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=jenkins_stack.yml jenkins 
  args: 
    chdir: "{{remote_temp}}"


    