- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: clean jenkins-workspace
  file: 
    path: /glusterfs_mnt/jenkins-workspace
    state: absent

- name: extract jenkins-workspace.tgz
  unarchive:
    src: "{{local_temp}}/jenkins-workspace.tgz"
    dest: /glusterfs_mnt/

# - name: modify directory owner
#   file: 
#     path: /glusterfs_mnt/jenkins-workspace
#     owner: 1000
#     group: 1000
#     recurse: yes
#     state: directory

- name: modify directory owner
  command: chown -R 1000:1000 /glusterfs_mnt/jenkins-workspace

- name: copy stack.yml to remote
  copy: 
    src: jenkins-stack.yml 
    dest: "{{remote_temp}}/jenkins-stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=jenkins-stack.yml jenkins 
  args: 
    chdir: "{{remote_temp}}"


    