- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: extract jenkins-workspace.tgz
  unarchive:
    src: "{{local_temp}}/jenkins-workspace.tgz"
    dest: /glusterfs_mnt/
    owner: 1000
    group: 1000 

- name: copy stack.yml to remote
  copy: 
    src: jenkins-stack.yml 
    dest: "{{remote_temp}}/jenkins-stack.yml"

# - name: deploy stack
#   command: docker stack deploy --compose-file=jenkins-stack.yml jenkins 
#   args: 
#     chdir: "{{remote_temp}}"


    