- name: create jenkins mount directory
  file: 
    path: /glusterfs_mnt/jenkins_data
    owner: 1000
    group: 1000  
    state: directory 

- name: create remote temp dir
  file: 
    path: "{{remote_temp}}"
    state: directory 

- name: copy stack.yml to remote
  copy: 
    src: jenkins-stack.yml 
    dest: "{{remote_temp}}/jenkins-stack.yml"

- name: deploy stack
  command: docker stack deploy --compose-file=jenkins-stack.yml jenkins 
  args: 
    chdir: "{{remote_temp}}"


    